name: MAIN

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

env:
 CI: true

jobs:
 build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm test
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CI: true
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      with:
        coverageCommand: npm run test:coverage
        debug: true
        verifyDownload: true
